version: '3.8'

services:
  web:
    container_name: blog_api_project_web
    build: .
    restart: always
    command: gunicorn blog_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db


  db:
    container_name: blog_api_project_postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  nginx:
    container_name: blog_api_project_nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: